const DRINK_SIZES = [
  { code: "S", value: "200 ml", addPrice: 0 },
  { code: "M", value: "300 ml", addPrice: 0.5 },
  { code: "L", value: "400 ml", addPrice: 1 },
];

const DESSERT_SIZES = [
  { code: "S", value: "50 g", addPrice: 0 },
  { code: "M", value: "100 g", addPrice: 0.5 },
  { code: "L", value: "200 g", addPrice: 1 },
];

const COFFEE_ADDITIVES = [
  { name: "Sugar", addPrice: 0.5 },
  { name: "Cinnamon", addPrice: 0.5 },
  { name: "Syrup", addPrice: 0.5 },
];

const TEA_ADDITIVES = [
  { name: "Sugar", addPrice: 0.5 },
  { name: "Lemon", addPrice: 0.5 },
  { name: "Syrup", addPrice: 0.5 },
];

const DESSERT_ADDITIVES = [
  { name: "Berries", addPrice: 0.5 },
  { name: "Nuts", addPrice: 0.5 },
  { name: "Jam", addPrice: 0.5 },
];

const PRODUCTS = [
  {
    id: "coffee-1",
    name: "Irish coffee",
    description: "Fragrant black coffee with Jameson Irish whiskey and whipped milk",
    price: 7,
    category: "coffee",
    image: "coffee-1.webp",
    sizes: DRINK_SIZES,
    additives: COFFEE_ADDITIVES,
  },
  {
    id: "coffee-2",
    name: "Kahlua coffee",
    description: "Classic coffee with milk and Kahlua liqueur under a cap of frothed milk",
    price: 7,
    category: "coffee",
    image: "coffee-2.webp",
    sizes: DRINK_SIZES,
    additives: COFFEE_ADDITIVES,
  },
  {
    id: "coffee-3",
    name: "Honey raf",
    description: "Espresso with frothed milk, cream and aromatic honey",
    price: 5.5,
    category: "coffee",
    image: "coffee-3.webp",
    sizes: DRINK_SIZES,
    additives: COFFEE_ADDITIVES,
  },
  {
    id: "coffee-4",
    name: "Ice cappuccino",
    description: "Cappuccino with soft thick foam in summer version with ice",
    price: 5,
    category: "coffee",
    image: "coffee-4.webp",
    sizes: DRINK_SIZES,
    additives: COFFEE_ADDITIVES,
  },
  {
    id: "coffee-5",
    name: "Espresso",
    description: "Classic black coffee",
    price: 4.5,
    category: "coffee",
    image: "coffee-5.webp",
    sizes: DRINK_SIZES,
    additives: COFFEE_ADDITIVES,
  },
  {
    id: "coffee-6",
    name: "Latte",
    description: "Espresso coffee with the addition of steamed milk and dense milk foam",
    price: 5.5,
    category: "coffee",
    image: "coffee-6.webp",
    sizes: DRINK_SIZES,
    additives: COFFEE_ADDITIVES,
  },
  {
    id: "coffee-7",
    name: "Latte macchiato",
    description: "Espresso with frothed milk and chocolate",
    price: 5.5,
    category: "coffee",
    image: "coffee-7.webp",
    sizes: DRINK_SIZES,
    additives: COFFEE_ADDITIVES,
  },
  {
    id: "coffee-8",
    name: "Coffee with cognac",
    description: "Fragrant black coffee with cognac and whipped cream",
    price: 6.5,
    category: "coffee",
    image: "coffee-8.webp",
    sizes: DRINK_SIZES,
    additives: COFFEE_ADDITIVES,
  },
  {
    id: "tea-1",
    name: "Moroccan",
    description: "Fragrant black tea with the addition of tangerine, cinnamon, honey, lemon and mint",
    price: 4.5,
    category: "tea",
    image: "tea-1.webp",
    sizes: DRINK_SIZES,
    additives: TEA_ADDITIVES,
  },
  {
    id: "tea-2",
    name: "Ginger",
    description: "Original black tea with fresh ginger, lemon and honey",
    price: 5,
    category: "tea",
    image: "tea-2.webp",
    sizes: DRINK_SIZES,
    additives: TEA_ADDITIVES,
  },
  {
    id: "tea-3",
    name: "Cranberry",
    description: "Invigorating black tea with cranberry and honey",
    price: 5,
    category: "tea",
    image: "tea-3.webp",
    sizes: DRINK_SIZES,
    additives: TEA_ADDITIVES,
  },
  {
    id: "tea-4",
    name: "Sea buckthorn",
    description: "Toning sweet black tea with sea buckthorn, fresh thyme and cinnamon",
    price: 5.5,
    category: "tea",
    image: "tea-4.webp",
    sizes: DRINK_SIZES,
    additives: TEA_ADDITIVES,
  },
  {
    id: "dessert-1",
    name: "Marble cheesecake",
    description: "Philadelphia cheese with lemon zest on a light sponge cake and red currant jam",
    price: 3.5,
    category: "dessert",
    image: "dessert-1.webp",
    sizes: DESSERT_SIZES,
    additives: DESSERT_ADDITIVES,
  },
  {
    id: "dessert-2",
    name: "Red velvet",
    description: "Layer cake with cream cheese frosting",
    price: 4,
    category: "dessert",
    image: "dessert-2.webp",
    sizes: DESSERT_SIZES,
    additives: DESSERT_ADDITIVES,
  },
  {
    id: "dessert-3",
    name: "Cheesecakes",
    description: "Soft cottage cheese pancakes with sour cream and fresh berries and sprinkled with powdered sugar",
    price: 4.5,
    category: "dessert",
    image: "dessert-3.webp",
    sizes: DESSERT_SIZES,
    additives: DESSERT_ADDITIVES,
  },
  {
    id: "dessert-4",
    name: "Creme brulee",
    description: "Delicate creamy dessert in a caramel basket with wild berries",
    price: 4,
    category: "dessert",
    image: "dessert-4.webp",
    sizes: DESSERT_SIZES,
    additives: DESSERT_ADDITIVES,
  },
  {
    id: "dessert-5",
    name: "Pancakes",
    description: "Tender pancakes with strawberry jam and fresh strawberries",
    price: 4.5,
    category: "dessert",
    image: "dessert-5.webp",
    sizes: DESSERT_SIZES,
    additives: DESSERT_ADDITIVES,
  },
  {
    id: "dessert-6",
    name: "Honey cake",
    description: "Classic honey cake with delicate custard",
    price: 4.5,
    category: "dessert",
    image: "dessert-6.webp",
    sizes: DESSERT_SIZES,
    additives: DESSERT_ADDITIVES,
  },
  {
    id: "dessert-7",
    name: "Chocolate cake",
    description: "Cake with hot chocolate filling and nuts with dried apricots",
    price: 5.5,
    category: "dessert",
    image: "dessert-7.webp",
    sizes: DESSERT_SIZES,
    additives: DESSERT_ADDITIVES,
  },
  {
    id: "dessert-8",
    name: "Black forest",
    description: "A combination of thin sponge cake with cherry jam and light chocolate mousse",
    price: 6.5,
    category: "dessert",
    image: "dessert-8.webp",
    sizes: DESSERT_SIZES,
    additives: DESSERT_ADDITIVES,
  },
];
